import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import DevConsole from "@/components/dev-console";

const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"]
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased ${geistSans.variable}`}
    >
      <body className="min-h-full">
        {children}
        <DevConsole />
      </body>
    </html>
  );
}
